name: insta_fake
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  get: ^4.6.5
  path_provider: ^2.0.11
  path: ^1.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  hive_generator: ^1.1.3
  build_runner: ^2.2.1

flutter:
  uses-material-design: true